name: FastAPI Docker Image CI/CD

on:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t invoice-aratiri .
    - name: docker-compose up
      run: docker-compose up -d
    - name: Print SSH key
      run: echo "${{ secrets.SSHKEY }}"
    - name: Configure SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa 64.23.229.251 >> ~/.ssh/known_hosts
    - name: SSH into vps update project
      uses: appleboy/ssh-action@master
      with:
        host: '64.23.229.251'
        username: 'root'
        key: ${{ secrets.SSHKEY }}
        script: |
          cd /var/www/invoice-aratiri
          git pull
          docker-compose down
          docker-compose up -d